mobile-questions html css
Nevadyaasha/catquiz pull request #3
Opened 2024-07-21 17:04 UTC by Nevadyaasha

2024-07-24 07:50 UTC, EugenNekrasov requested changes

2024-07-24 07:50 UTC, EugenNekrasov commented on questions.css
> +
Не хватает форматирования

2024-07-24 07:50 UTC, EugenNekrasov commented on questions.html
> +        <div
Т.к. это форма, то она нуждается в тэге `<form>` вместо этого дива. Почитай про их настройку.

2024-07-24 07:50 UTC, EugenNekrasov commented on questions.html
> +                <input class="form-check-input" type="checkbox" id="iquestion1answer2" value="option1">
Тут `id` с ошибкой. Надо прокликать все лейблы и убедиться, что фокус встаёт на связанных инпутах.

2024-07-24 07:50 UTC, EugenNekrasov commented on questions.html
> +        <h1 class="mx-auto mt-4 mb-3 text-start"><strong>What do oriental cats look like?</strong></h1>
`<strong>` нужен не столько для зрячих, сколько для читалок. Такой текст читается громче и с акцентом. Но `<h1>` итак выделяется голосом. Выходит масло-масляное. Если нужна стилизация для зрячих, лучше используй CSS.

2024-07-24 07:50 UTC, EugenNekrasov commented on questions.html
> +                <label class="form-check-label" for="question1answer1">Long, lean, graceful body</label>
Ниже по странице ты вкладывала `<input>` в `<label>` и было проще - див становился не нужен, `id` + `for` тоже.  Почему бы не сделать так же и тут?

2024-07-24 07:50 UTC, EugenNekrasov commented on questions.html
> +                <input class="form-check-input" type="checkbox" id="iquestion1answer2" value="option1">
У всех полей ввода одинаковый `value`. Надо хотя бы разный, а лучше по какой-то системе - 0,1,2,3 или "green eyes", "big ears" и т.д.

2024-07-24 07:50 UTC, EugenNekrasov commented on questions.html
> +                <strong>Confirm</strong></button>
`<strong>` снова не в тему)

2024-07-24 07:50 UTC, EugenNekrasov commented on questions.html
> +            <button type="button" id="btn-info" class="btn_lightblue btn btn-info btn-lg my-5 px-5 mx-auto">
Для чего кнопке `id`? Причём, он повторяется у каждой кнопки, а должен быть уникальным на странице.

2024-07-24 07:50 UTC, EugenNekrasov commented on questions.html
> +        <input type="range" min="0" max="30" step="1" class="form-range w-75 mx-auto d-block" id="cquestion5">
Опечатка в `id`.

2024-07-24 07:50 UTC, EugenNekrasov commented on questions.html
> +                        <p>Chill alone</p>
А нужен ли тут `<p>`? CSS-классы он не несёт с собой, а если убрать - ничего не изменился.

2024-07-24 07:50 UTC, EugenNekrasov commented on questions.html
> +                    <input class="form-check-input" type="radio" name="question6pair1" id="question6pair1answer1" value="option1">
Такие `id` тяжело читать. Раз `<input>` уже внутри `<label>`, может, избавиться от `id`?

2024-08-08 12:34 UTC, Nevadyaasha commented on questions.html
> +                <label class="form-check-label" for="question1answer1">Long, lean, graceful body</label>
переделала все так и снесла for/id

2024-08-08 12:49 UTC, Nevadyaasha commented on questions.html
> +        <h1 class="mx-auto mt-4 mb-3 text-start"><strong>What do oriental cats look like?</strong></h1>
Убрала, добавила стили на h1 и .btn

2024-08-08 12:50 UTC, Nevadyaasha commented on questions.html
> +            <button type="button" id="btn-info" class="btn_lightblue btn btn-info btn-lg my-5 px-5 mx-auto">
Снесла

2024-08-08 12:53 UTC, Nevadyaasha commented on questions.html
> +                        <p>Chill alone</p>
Зачем-то нужен был, но сейчас не нашла зачем, снесла

2024-08-08 12:57 UTC, Nevadyaasha commented
https://nevadyaasha.github.io/catquiz/

2024-08-09 08:11 UTC, EugenNekrasov requested changes

2024-08-09 08:11 UTC, EugenNekrasov commented on questions.html
> +                    <input class="form-check-input" type="checkbox" value="option4">
`value="option4"` уже есть выше.

2024-08-09 08:11 UTC, EugenNekrasov commented on questions.html
> +                        <option value="3">Siamese cat</option>
`value="3"` уже есть выше.

2024-08-09 08:11 UTC, EugenNekrasov commented on questions.html
> +                        <option value="3">Siamese cat</option>
`value="3"` уже есть выше.

2024-08-09 08:11 UTC, EugenNekrasov commented on questions.html
> +                        <option value="3">Siamese cat</option>
`value="3"` уже есть выше.

2024-08-09 08:11 UTC, EugenNekrasov commented on questions.html
> +                        <option value="3">Siamese cat</option>
`value="3"` уже есть выше.

2024-08-09 08:36 UTC, EugenNekrasov approved these changes

2024-08-09 08:36 UTC, merged